-- Seed scale definitions and questions.
-- Safe to run multiple times (uses ON CONFLICT DO NOTHING).

INSERT INTO scales (id, code, name, description, is_active, created_at, updated_at) VALUES
('scale_cesd', 'CESD20', 'CES-D 憂鬱量表', '20 題，4/8/12/16 為反向題', true, NOW(), NOW()),
('scale_bsrs5', 'BSRS5', 'BSRS-5 簡式健康量表', '5 題心情溫度計', true, NOW(), NOW()),
('scale_sats', 'SATS10', 'SATS 消沉指數', '10 題消沉狀態量表', true, NOW(), NOW()),
('scale_aq10', 'AQ10', 'AQ-10 孤獨症量表', '10 題自閉光譜特質篩檢', true, NOW(), NOW()),
('scale_pcq12', 'PCQ12', '心理資本量表', 'Hope / Efficacy / Resilience / Optimism', true, NOW(), NOW()),
('scale_cdrisc25', 'CDRISC25', 'CD-RISC 復原力量表', '25 題復原力', true, NOW(), NOW()),
('scale_pansi', 'PANSI14', 'PANSI-C 自殺意念量表', '正向/負向自殺意念', true, NOW(), NOW()),
('scale_bss', 'BSS21', 'BSS 自殺意念量表', '21 題自殺意念評估', true, NOW(), NOW())
ON CONFLICT (id) DO NOTHING;

INSERT INTO scale_questions (id, scale_id, "order", text, is_reverse) VALUES
('cesd_1','scale_cesd',1,'我覺得心情不好',false),
('cesd_2','scale_cesd',2,'我覺得做任何事情都很吃力',false),
('cesd_3','scale_cesd',3,'我的睡眠不好',false),
('cesd_4','scale_cesd',4,'我覺得和以前一樣快樂',true),
('cesd_5','scale_cesd',5,'我感到孤單',false),
('cesd_6','scale_cesd',6,'我覺得未來沒有希望',false),
('cesd_7','scale_cesd',7,'我覺得很難專心做事',false),
('cesd_8','scale_cesd',8,'我對生活感到滿意',true),
('cesd_9','scale_cesd',9,'我覺得心情低落、沮喪',false),
('cesd_10','scale_cesd',10,'我覺得自己一無是處',false),
('cesd_11','scale_cesd',11,'我覺得生活沒有意義',false),
('cesd_12','scale_cesd',12,'我仍然享受生活中的事情',true),
('cesd_13','scale_cesd',13,'我覺得自己沒有價值',false),
('cesd_14','scale_cesd',14,'我覺得別人對我不友善',false),
('cesd_15','scale_cesd',15,'我常常想哭',false),
('cesd_16','scale_cesd',16,'我覺得自己充滿活力',true),
('cesd_17','scale_cesd',17,'我感到悲傷',false),
('cesd_18','scale_cesd',18,'我覺得別人不喜歡我',false),
('cesd_19','scale_cesd',19,'我無法擺脫憂鬱的情緒',false),
('cesd_20','scale_cesd',20,'我覺得生活過得不好',false),
('bsrs_1','scale_bsrs5',1,'感到緊張、焦慮或不安',false),
('bsrs_2','scale_bsrs5',2,'感到情緒低落、心情不好',false),
('bsrs_3','scale_bsrs5',3,'覺得容易生氣或煩躁',false),
('bsrs_4','scale_bsrs5',4,'感到睡眠困難（難以入睡、易醒或睡不好）',false),
('bsrs_5','scale_bsrs5',5,'覺得生活壓力很大、事情變得困難',false),
('sats_1','scale_sats',1,'我最近經常感到情緒低落',false),
('sats_2','scale_sats',2,'我對原本感興趣的事情提不起勁',false),
('sats_3','scale_sats',3,'我覺得每天都很疲倦',false),
('sats_4','scale_sats',4,'我覺得生活缺乏動力',false),
('sats_5','scale_sats',5,'我覺得心情空虛',false),
('sats_6','scale_sats',6,'我對未來缺乏期待',false),
('sats_7','scale_sats',7,'我做事時感到精神不集中',false),
('sats_8','scale_sats',8,'我覺得自己缺乏活力',false),
('sats_9','scale_sats',9,'我覺得生活沒有什麼意義',false),
('sats_10','scale_sats',10,'我覺得自己陷入一種消沉的狀態',false),
('aq_1','scale_aq10',1,'我比較喜歡獨自做事情，而不是和別人一起',false),
('aq_2','scale_aq10',2,'我對細節特別敏感',false),
('aq_3','scale_aq10',3,'我可以輕鬆同時處理多件事情',true),
('aq_4','scale_aq10',4,'我覺得理解別人的感受很困難',false),
('aq_5','scale_aq10',5,'我對某些事情會產生非常強烈的興趣',false),
('aq_6','scale_aq10',6,'我不太擅長社交場合',false),
('aq_7','scale_aq10',7,'我可以輕易從別人的表情判斷他們的感受',true),
('aq_8','scale_aq10',8,'我覺得與人閒聊是一件困難的事',false),
('aq_9','scale_aq10',9,'我能迅速理解他人的意圖',true),
('aq_10','scale_aq10',10,'我不太在意與人建立親密關係',false),
('pcq_1','scale_pcq12',1,'當遇到困難時，我能想到多種解決方法',false),
('pcq_2','scale_pcq12',2,'即使遇到阻礙，我仍能朝目標前進',false),
('pcq_3','scale_pcq12',3,'我對達成目標充滿希望',false),
('pcq_4','scale_pcq12',4,'我對自己完成重要任務有信心',false),
('pcq_5','scale_pcq12',5,'面對挑戰時，我相信自己有能力處理',false),
('pcq_6','scale_pcq12',6,'我能有效解決問題',false),
('pcq_7','scale_pcq12',7,'遭遇挫折後，我能很快恢復',false),
('pcq_8','scale_pcq12',8,'困難不會輕易擊倒我',false),
('pcq_9','scale_pcq12',9,'我能從失敗中學習',false),
('pcq_10','scale_pcq12',10,'我對未來抱持正向期待',false),
('pcq_11','scale_pcq12',11,'我通常相信事情會有好結果',false),
('pcq_12','scale_pcq12',12,'即使遇到困境，我仍保持樂觀',false),
('cdr_1','scale_cdrisc25',1,'我能適應改變',false),
('cdr_2','scale_cdrisc25',2,'我能應付壓力',false),
('cdr_3','scale_cdrisc25',3,'我不容易被擊倒',false),
('cdr_4','scale_cdrisc25',4,'我能從困難中恢復',false),
('cdr_5','scale_cdrisc25',5,'我相信自己能克服逆境',false),
('cdr_6','scale_cdrisc25',6,'我能忍受不確定性',false),
('cdr_7','scale_cdrisc25',7,'我有清楚的人生目標',false),
('cdr_8','scale_cdrisc25',8,'我在壓力下仍能保持專注',false),
('cdr_9','scale_cdrisc25',9,'我能從過去的失敗中學習',false),
('cdr_10','scale_cdrisc25',10,'我面對困難時不會放棄',false),
('cdr_11','scale_cdrisc25',11,'我能控制負面情緒',false),
('cdr_12','scale_cdrisc25',12,'我能在挫折後重新振作',false),
('cdr_13','scale_cdrisc25',13,'我能保持冷靜',false),
('cdr_14','scale_cdrisc25',14,'我能有效解決問題',false),
('cdr_15','scale_cdrisc25',15,'我覺得自己很堅強',false),
('cdr_16','scale_cdrisc25',16,'我能接受事情不如預期',false),
('cdr_17','scale_cdrisc25',17,'我能在逆境中成長',false),
('cdr_18','scale_cdrisc25',18,'我能找到支持自己的力量',false),
('cdr_19','scale_cdrisc25',19,'我能承受情緒上的痛苦',false),
('cdr_20','scale_cdrisc25',20,'我能維持正向態度',false),
('cdr_21','scale_cdrisc25',21,'我能適應生活變化',false),
('cdr_22','scale_cdrisc25',22,'我能克服生活中的障礙',false),
('cdr_23','scale_cdrisc25',23,'我相信自己的能力',false),
('cdr_24','scale_cdrisc25',24,'我能面對未來的挑戰',false),
('cdr_25','scale_cdrisc25',25,'我能持續前進',false),
('pansi_1','scale_pansi',1,'我曾想過結束自己的生命',false),
('pansi_2','scale_pansi',2,'我覺得活著沒有意義',false),
('pansi_3','scale_pansi',3,'我曾認真考慮過自殺',false),
('pansi_4','scale_pansi',4,'我感到絕望',false),
('pansi_5','scale_pansi',5,'我覺得自己是別人的負擔',false),
('pansi_6','scale_pansi',6,'我不想再活下去',false),
('pansi_7','scale_pansi',7,'我覺得沒有任何出路',false),
('pansi_8','scale_pansi',8,'我覺得死亡是解脫',false),
('pansi_9','scale_pansi',9,'即使很痛苦，我仍不想傷害自己',true),
('pansi_10','scale_pansi',10,'我覺得未來仍有希望',true),
('pansi_11','scale_pansi',11,'我能找到活下去的理由',true),
('pansi_12','scale_pansi',12,'我在乎重要的人',true),
('pansi_13','scale_pansi',13,'我相信困難會過去',true),
('pansi_14','scale_pansi',14,'我願意尋求幫助',true),
('bss_1','scale_bss',1,'活著的渴望',false),
('bss_2','scale_bss',2,'對死亡的渴望',false),
('bss_3','scale_bss',3,'活下去或死亡的理由',false),
('bss_4','scale_bss',4,'自殺意念的強度',false),
('bss_5','scale_bss',5,'自殺意念的頻率',false),
('bss_6','scale_bss',6,'自我控制能力',false),
('bss_7','scale_bss',7,'對自殺的抑制因素',false),
('bss_8','scale_bss',8,'對死亡的態度',false),
('bss_9','scale_bss',9,'是否有自殺計畫',false),
('bss_10','scale_bss',10,'自殺方法的可行性',false),
('bss_11','scale_bss',11,'是否做過準備行為',false),
('bss_12','scale_bss',12,'是否寫過遺書',false),
('bss_13','scale_bss',13,'是否預期會死亡',false),
('bss_14','scale_bss',14,'是否隱瞞自殺意念',false),
('bss_15','scale_bss',15,'自殺意念持續時間',false),
('bss_16','scale_bss',16,'自殺行為的可能性',false),
('bss_17','scale_bss',17,'對家人的影響考量',false),
('bss_18','scale_bss',18,'對未來的看法',false),
('bss_19','scale_bss',19,'求助意願',false),
('bss_20','scale_bss',20,'自殺想法的可控性',false),
('bss_21','scale_bss',21,'過去是否有自殺行為',false)
ON CONFLICT (id) DO NOTHING;
